# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71ba7a746c0f27d3e79b2052ad5dff214c955a4f030b35365e342b4590066f6f99e68fec37a193f0740c004c51ed2cea9f61517c4124720bdcb84e7b2ae4e3e1

test:
  secret_key_base: 19b4a61d5c544456660cfe9296b9a48dd1cf99e869ccefbb5fe7e569eee6b5f08d8023613867b493d208cc04af135bffce621bf6a3eb4e00edf382d7d9917a06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
